spring:
  application:
    name: omoide-memory
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - requestId=%X{requestId} requestUrl=%X{requestUrl} requestMethod=%X{requestMethod} userAgent=%X{userAgent} - %msg%n"
